version: '3'

services:
  rs01:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/parteaga/Developer/krowdy/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /Users/parteaga/Developer/krowdy/redis/data:/data